NAME_ENV_FILE = ".env"
PREFIX_REDIS_CACHE = "fastapi-cache-ev"

DEFAULT_LIMIT = 100
DEFAULT_OFFSET = 0
VALUE_NOT_LESS = 0
DEFAULT_COUNT_TAGS = 5

EXPIRES_HOUR_CACHE_ON_SECONDS = 3600
EXPIRES_10_MIN_CACHE_ON_SECONDS = 600
