"""add cost ee

Revision ID: dc3fbc32d9d6
Revises: 5218e4685155
Create Date: 2023-12-14 12:03:30.570560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc3fbc32d9d6"
down_revision = "5218e4685155"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("cost_ee", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("cost_ee", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "cost_ee")
    op.drop_column("cities", "cost_ee")
    # ### end Alembic commands ###
