"""Edit city

Revision ID: 3c53bbedd060
Revises: 74192d398ae2
Create Date: 2023-10-25 00:50:20.036062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c53bbedd060'
down_revision = '74192d398ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('display_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'display_name')
    
    # ### end Alembic commands ###
