"""add growth

Revision ID: 73d387381fb9
Revises: fa40f86a63fb
Create Date: 2023-12-13 12:15:24.671682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73d387381fb9"
down_revision = "fa40f86a63fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "growth_cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("growth_cars")
    # ### end Alembic commands ###
