"""Edit region

Revision ID: 12145f2cbccc
Revises: e3df0c99aa43
Create Date: 2023-11-03 12:42:42.516788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12145f2cbccc'
down_revision = 'e3df0c99aa43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_regions_geometry', 'regions', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_regions_location', 'regions', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_regions_location', table_name='regions', postgresql_using='gist')
    op.drop_index('idx_regions_geometry', table_name='regions', postgresql_using='gist')
    
    # ### end Alembic commands ###
