"""new

Revision ID: 7bfccd82e5ce
Revises: 0c06a24021bd
Create Date: 2023-10-24 21:05:48.301270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_bigquery

# revision identifiers, used by Alembic.
revision = '7bfccd82e5ce'
down_revision = '0c06a24021bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('location', sqlalchemy_bigquery.geography.GEOGRAPHY(), nullable=True),
    sa.Column('geometry', sqlalchemy_bigquery.geography.GEOGRAPHY(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('north', sa.Float(), nullable=True),
    sa.Column('south', sa.Float(), nullable=True),
    sa.Column('east', sa.Float(), nullable=True),
    sa.Column('west', sa.Float(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('cities')
    # ### end Alembic commands ###
