"""add growth to regions

Revision ID: 34e1fb295bda
Revises: 73d387381fb9
Create Date: 2023-12-13 12:24:47.457117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34e1fb295bda"
down_revision = "73d387381fb9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("regions", sa.Column("growth_car_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "regions", "growth_cars", ["growth_car_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "regions", type_="foreignkey")
    op.drop_column("regions", "growth_car_id")

    # ### end Alembic commands ###
