"""add growth

Revision ID: 64ffc1f63284
Revises: 8ba090dcb550
Create Date: 2023-12-13 12:35:55.010985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ffc1f63284'
down_revision = '8ba090dcb550'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('growth_car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'regions', 'growth_cars', ['growth_car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.drop_column('regions', 'growth_car_id')
    
    # ### end Alembic commands ###
