"""add growth

Revision ID: 5218e4685155
Revises: 64ffc1f63284
Create Date: 2023-12-13 12:43:59.979561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5218e4685155'
down_revision = '64ffc1f63284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('growth_car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cities', 'growth_cars', ['growth_car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_column('cities', 'growth_car_id')
    
    # ### end Alembic commands ###
