"""Edit city

Revision ID: 74192d398ae2
Revises: 7bfccd82e5ce
Create Date: 2023-10-25 00:49:30.812190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74192d398ae2'
down_revision = '7bfccd82e5ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    
    # ### end Alembic commands ###
