"""edit growth

Revision ID: cd13400f1569
Revises: 34e1fb295bda
Create Date: 2023-12-13 12:29:10.224893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd13400f1569'
down_revision = '34e1fb295bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('regions_growth_car_id_fkey', 'regions', type_='foreignkey')
    op.drop_column('regions', 'growth_car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('growth_car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('regions_growth_car_id_fkey', 'regions', 'growth_cars', ['growth_car_id'], ['id'])
    
    # ### end Alembic commands ###
