"""Edit regions

Revision ID: e3df0c99aa43
Revises: baebf3ecdfdc
Create Date: 2023-11-01 22:53:39.674218

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_bigquery


# revision identifiers, used by Alembic.
revision = 'e3df0c99aa43'
down_revision = 'baebf3ecdfdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('location', sqlalchemy_bigquery.geography.GEOGRAPHY(), nullable=True))
    op.add_column('regions', sa.Column('geometry', sqlalchemy_bigquery.geography.GEOGRAPHY(), nullable=True))
    op.add_column('regions', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('regions', sa.Column('north', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('south', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('east', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('west', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('display_name', sa.Text(), nullable=True))
    op.add_column('regions', sa.Column('importance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'importance')
    op.drop_column('regions', 'display_name')
    op.drop_column('regions', 'west')
    op.drop_column('regions', 'east')
    op.drop_column('regions', 'south')
    op.drop_column('regions', 'north')
    op.drop_column('regions', 'type')
    op.drop_column('regions', 'geometry')
    op.drop_column('regions', 'location')
    
    # ### end Alembic commands ###
