"""Edit city

Revision ID: baebf3ecdfdc
Revises: 3c53bbedd060
Create Date: 2023-10-28 16:31:58.505982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baebf3ecdfdc'
down_revision = '3c53bbedd060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('is_top', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'is_top')
    
    # ### end Alembic commands ###
