"""add growth

Revision ID: 8ba090dcb550
Revises: cd13400f1569
Create Date: 2023-12-13 12:34:43.780177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba090dcb550'
down_revision = 'cd13400f1569'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('growth_cars')
    # ### end Alembic commands ###
