"""Edit city

Revision ID: 67abc2db1fb3
Revises: 12145f2cbccc
Create Date: 2023-11-03 12:44:40.340568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67abc2db1fb3'
down_revision = '12145f2cbccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_cities_geometry', 'cities', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_cities_location', 'cities', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cities_location', table_name='cities', postgresql_using='gist')
    op.drop_index('idx_cities_geometry', table_name='cities', postgresql_using='gist')
    
    # ### end Alembic commands ###
