"""Add evs

Revision ID: fa40f86a63fb
Revises: 67abc2db1fb3
Create Date: 2023-11-19 22:10:07.859107

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa40f86a63fb'
down_revision = '67abc2db1fb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.String(length=255), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('operator', sa.JSON(), nullable=True),
    sa.Column('data_provider', sa.JSON(), nullable=True),
    sa.Column('usage_type', sa.JSON(), nullable=True),
    sa.Column('сonnections', sa.JSON(), nullable=True),
    sa.Column('status_type', sa.JSON(), nullable=True),
    sa.Column('submission_status_type', sa.JSON(), nullable=True),
    sa.Column('number_points', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.JSON(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('ev_stations')
    # ### end Alembic commands ###
